
Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 10008, host: 10008
  
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 18080, host: 18080
  config.vm.network "forwarded_port", guest: 8988, host: 8988
  config.vm.network "forwarded_port", guest: 8989, host: 8989

  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9092, host: 9092
  config.vm.network "forwarded_port", guest: 2181, host: 2181
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  # Cassandra
  config.vm.network "forwarded_port", guest: 7000, host: 7000
  config.vm.network "forwarded_port", guest: 7001, host: 7001
  config.vm.network "forwarded_port", guest: 7199, host: 7199
  config.vm.network "forwarded_port", guest: 9042, host: 9042
  config.vm.network "forwarded_port", guest: 9160, host: 9160

  for i in 8030..8033
    config.vm.network :forwarded_port, guest: i, host: i
  end

  config.vm.network "forwarded_port", guest: 8040, host: 8040
  config.vm.network "forwarded_port", guest: 8042, host: 8042
  config.vm.network "forwarded_port", guest: 8088, host: 8088
  config.vm.network "forwarded_port", guest: 49707, host: 49707
  config.vm.network "forwarded_port", guest: 50010, host: 50011
  config.vm.network "forwarded_port", guest: 50020, host: 50020
  config.vm.network "forwarded_port", guest: 50070, host: 50070
  config.vm.network "forwarded_port", guest: 50075, host: 50075
  config.vm.network "forwarded_port", guest: 50090, host: 50090
  config.vm.network "forwarded_port", guest: 22, host: 9922

  config.vm.network "forwarded_port", guest: 4040, host: 4040

  config.vm.box = "aalkilani/spark-kafka-cassandra-applying-lambda-architecture/lambda_arch"

  config.vm.hostname = "lambda-pluralsight"

  config.vm.provision "docker-images", type: "shell", run: "always", inline: <<-SHELLPRE
    docker restart zookeeper
    docker restart spark-1.6.3
    docker restart cassandra
    docker restart zeppelin
    docker restart kafka
  SHELLPRE

  config.vm.provision "image-fixes", type: "shell", run: "once", path: "fixes.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end

end
